version: "2"

services:
  lecternDb:
    image: "mongo:4"
    ports:
      - "27272:27017"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lectern
volumes:
  mongodb_data:
    driver: local
